### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by sakurai-youhei** [python-hyper/hyperframe#124]
**Issue**

[Published documentation](https://python-hyper.org/hyperframe/en/latest/) gives wrong instruction of the way to decode lyrics of HTTP2 using hyperframe. (btw, thank you for your great work!)

**Suggestion**

Update [source of documentation](https://github.com/python-hyper/hyperframe/blob/master/docs/source/index.rst) with like below code which is based on [this test code](https://github.com/python-hyper/hyperframe/blob/master/test/test_frames.py#L13).

```python
import hyperframe.frame

f = hyperframe.frame.DataFrame(stream_id=5)
f.data = b'some binary data'
f.flags.add('END_STREAM')
f.flags.add('PADDED')
f.padding_length = 30

data = f.serialize()

new_frame, length = hyperframe.frame.Frame.parse_frame_header(data[:9])
new_frame.parse_body(memoryview(data[9:9 + length]))
```

**Why this issue**

[This momentum](http://www.catb.org/esr/faqs/hacker-howto.html#respect2). :)

**Comment by Kriechi** [comment]
Thanks for reporting this - what exactly is outdated?
I couldn't find a difference - maybe you could send a PR so we can see the diff?

**Comment by sakurai-youhei** [comment]
After opening PR, I come to think below would be better because slicing memoryview is smarter than just transforming chunk of bytes into memoryview. Please take whatever you think the best.

```python
data = f.serialize()
view = memoryview(data)

new_frame, length = hyperframe.frame.Frame.parse_frame_header(view[:9])
new_frame.parse_body(view[9:9 + length])
```
