### ISSUE TITLE
Question: frame length field

### ISSUE THREAD

**Issue by mrpre** [python-hyper/hyperframe#140]
The annotation shows that the length filed should be 24 bit (3 bytes). Why the implement just use 2 bytes (length = (fields[0] << 8) + fields[1] ) ?
https://github.com/python-hyper/hyperframe/blob/809ffe75b1fe35e7336355ea27b65f2cbbe234d5/hyperframe/frame.py#L112-L115

**Comment by sethmlarson** [comment]
If you look at the struct above you'll notice fields[0] is 2 bytes long and fields[1] is 1 byte long adding up to 24 bits.
