### ISSUE TITLE
Broken hyperlinks

### ISSUE THREAD

**Issue by bricewge** [python-hyper/hyperframe#141]
Github's description and PYPI's hompage links returns 403, it should probably be https://hyperframe.readthedocs.io/en/latest/ instead.

Similar issue as https://github.com/python-hyper/hpack/issues/233

**Comment by Kriechi** [comment]
I changed the Github description text.
PyPi is based on the setup.py of the most recent release.
@pgjones might be able to change hpack's Github description.

**Comment by pgjones** [comment]
Sadly I cannot change hpack's

**Comment by Kriechi** [comment]
This should be fixed now.
