### ISSUE TITLE
Question: How do I make a request frame?

### ISSUE THREAD

**Issue by Galgamins** [python-hyper/hyperframe#162]
Say a GET or a POST frame? Couldn't find any examples of frames being constructed except [this](https://github.com/python-hyper/hyperframe/blob/master/docs/source/index.rst) which seems to be super generic.

**Comment by Kriechi** [comment]
hyperframe only provides the low-level framing for the HTTP/2 protocol.
It sounds like you are looking for a higher-level API and library, in this case take a look at [h2](https://github.com/python-hyper/h2) which uses [hyperframe](https://github.com/python-hyper/hyperframe) and [hpack](https://github.com/python-hyper/hpack).
